### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by siascone** [brcodington78/FewTrails#2]
# MVP List
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
## Comments

**Comment by siascone** [comment]
- missing description sentence of the app
- missing details bullets for feature functionality
- missing time estimates and completion dates
Use bluebird wiki for reference

**Comment by siascone** [comment]
- formatting issues (in markdown asterisks need a space between them and the sentence that they are bulleting) (see bluebird for reference on all formatting)
- missing estimates to completion of features (i.e. 2 days, 1 day, 0.5 days etc)
- missing bullets indicating what can be deleted by a user (i.e. users can delete reviews, photos, remove favorite trails etc.)

**Comment by siascone** [comment]
Looks good
